let products=[];
const saved=JSON.parse(localStorage.getItem('akfix_receiving_current')||'{}');
const state={open:null,query:'',complete:false,fileName:saved.fileName||'',rows:[]};
if(Array.isArray(saved.products)&&saved.products.length){products=saved.products;state.rows=saved.rows||makeRows(products)}
const app=document.querySelector('#app');let scannerStream=null,scannerFrame=0,scanAllocation=null;
const esc=(s='')=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function makeRows(items){return items.map(p=>({done:false,alloc:[{qty:p.plan,expiry:'',cell:'',comment:''}]}))}
function persist(){localStorage.setItem('akfix_receiving_current',JSON.stringify({fileName:state.fileName,products,rows:state.rows}))}
const normalize=value=>String(value??'').trim();
const number=value=>{const parsed=Number(normalize(value).replace(/\s/g,'').replace(',','.'));return Number.isFinite(parsed)?parsed:0};
const column=(headers,patterns)=>headers.findIndex(value=>patterns.some(pattern=>pattern.test(normalize(value))));
async function loadExcel(file){
 const data=await file.arrayBuffer(),book=XLSX.read(data,{type:'array'}),sheet=book.Sheets[book.SheetNames[0]],grid=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});if(!grid.length)throw new Error('EMPTY');
 let headerIndex=grid.findIndex(row=>row.some(value=>/артикул|номенклат|товар|колич|план/i.test(normalize(value))));if(headerIndex<0)headerIndex=0;
 const headers=grid[headerIndex].map(normalize),articleCol=column(headers,[/артикул/i,/код/i]),nameCol=column(headers,[/номенклат/i,/наименован/i,/товар/i]),planCol=column(headers,[/план/i,/колич/i,/шт/i]),packCol=column(headers,[/упаков/i,/единиц/i]);if(nameCol<0&&articleCol<0)throw new Error('HEADERS');
 const rows=grid.slice(headerIndex+1).map(row=>({article:normalize(row[articleCol>=0?articleCol:0]),name:normalize(row[nameCol>=0?nameCol:1]),plan:number(row[planCol>=0?planCol:2]),pack:packCol>=0?normalize(row[packCol]):''})).filter(item=>(item.article||item.name)&&item.plan>0);if(!rows.length)throw new Error('ROWS');
 products=rows;state.rows=makeRows(rows);state.fileName=file.name;state.open=0;state.complete=false;persist();render();toast(`Загружено позиций: ${rows.length}`)
}
function exportExcel(){const rows=[];state.rows.forEach((row,i)=>row.alloc.forEach(a=>rows.push({'Номенклатура':products[i].name,'Артикул':products[i].article,'Срок годности (месяц и год)':a.expiry,'Фактически принято':Number(a.qty),'Ячейка':a.cell,'Комментарий':a.comment})));const sheet=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Приёмка');XLSX.writeFile(book,`Приёмка — ${state.fileName.replace(/\.[^.]+$/,'')||'результат'}.xlsx`)}
function stopScanner(){cancelAnimationFrame(scannerFrame);scannerFrame=0;scannerStream?.getTracks().forEach(track=>track.stop());scannerStream=null;document.querySelector('#scannerVideo').srcObject=null;document.querySelector('#scanner').hidden=true}
async function startScanner(index){if(!('BarcodeDetector'in window))return toast('Сканер не поддерживается — введите ячейку вручную');scanAllocation=index;const overlay=document.querySelector('#scanner'),video=document.querySelector('#scannerVideo'),hint=document.querySelector('#scannerHint');overlay.hidden=false;hint.textContent='Запрашиваем доступ к камере…';try{const formats=await BarcodeDetector.getSupportedFormats(),wanted=['qr_code','code_128','code_39','ean_13','ean_8','data_matrix'].filter(x=>formats.includes(x)),detector=new BarcodeDetector(wanted.length?{formats:wanted}:undefined);scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=scannerStream;await video.play();hint.textContent='Наведите камеру на код ячейки';const detect=async()=>{if(!scannerStream)return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){state.rows[state.open].alloc[scanAllocation].cell=codes[0].rawValue.trim();persist();stopScanner();render();toast(`Ячейка: ${codes[0].rawValue.trim()}`);return}}catch{}scannerFrame=requestAnimationFrame(detect)};detect()}catch(error){stopScanner();toast(error.name==='NotAllowedError'?'Разрешите доступ к камере':'Не удалось открыть камеру')}}
function allocation(a,j,total){return`<section class="allocation"><h3>Размещение ${total>1?j+1:''}${total>1?`<button class="remove" data-remove="${j}">Удалить</button>`:''}</h3><div class="grid"><label class="field">Фактически принято<input inputmode="numeric" data-key="qty" data-a="${j}" value="${esc(a.qty)}"></label><label class="field">Срок годности · месяц и год<input type="month" data-key="expiry" data-a="${j}" value="${esc(a.expiry)}"></label><label class="field">Ячейка хранения<span class="cell-control"><input data-key="cell" data-a="${j}" placeholder="Например, A-01-03" value="${esc(a.cell)}"><button type="button" class="scan-cell" data-scan="${j}">Сканировать</button></span></label><label class="field full">Комментарий<input data-key="comment" data-a="${j}" placeholder="Необязательно" value="${esc(a.comment)}"></label></div></section>`}
function header(){return`<header class="top"><img src="/assets/logo.svg" alt="AKFIX"><span><b>Приёмка</b><small>Склад</small></span><div class="top-actions"><button class="header-action" id="newExcel">Загрузить Excel</button><button class="header-action exit" id="exit">Выйти</button></div><input id="excelFile" type="file" accept=".xlsx,.xls,.csv" hidden></header>`}
function emptyView(){app.innerHTML=`<div class="shell">${header()}<section class="upload-empty"><div class="upload-mark">XLSX</div><h1>Нет активной приёмки</h1><p>Загрузите актуальный Excel-файл с товарами и плановым количеством.</p><button class="btn primary" id="uploadExcel">Загрузить Excel</button><small>Поддерживаются XLSX, XLS и CSV</small></section></div>`;wireHeader();document.querySelector('#uploadExcel').onclick=()=>document.querySelector('#excelFile').click()}
function render(){if(!products.length)return emptyView();if(state.complete){app.innerHTML=`<div class="shell">${header()}<div class="complete"><div class="check">✓</div><h2>Приёмка завершена</h2><p>${esc(state.fileName)} · принято ${state.rows.reduce((s,r)=>s+r.alloc.reduce((x,a)=>x+Number(a.qty||0),0),0).toLocaleString('ru-RU')} шт.</p><button class="btn primary export" id="export">Скачать Excel</button><button class="btn outline" id="return">Вернуться к позициям</button></div></div>`;wireHeader();document.querySelector('#export').onclick=exportExcel;document.querySelector('#return').onclick=()=>{state.complete=false;render()};return}
 const done=state.rows.filter(r=>r.done).length,total=products.length,filtered=products.map((p,i)=>({...p,i})).filter(p=>(p.article+' '+p.name).toLowerCase().includes(state.query.toLowerCase()));
 app.innerHTML=`<div class="shell">${header()}<section class="summary"><h2>${esc(state.fileName.replace(/\.[^.]+$/,''))}</h2><p>${done} из ${total} позиций · данные из Excel</p><div class="progress"><div class="track"><div class="bar" style="width:${done/total*100}%"></div></div><b>${Math.round(done/total*100)}%</b></div></section><input class="search" placeholder="Поиск по артикулу или названию" value="${esc(state.query)}"><div class="labels"><span>Артикул / товар</span><span>План</span><span>Статус</span></div><section>${filtered.map(p=>{const r=state.rows[p.i],open=state.open===p.i;return`<article class="item ${open?'open':''} ${r.done?'done':''}"><div class="item-head" data-open="${p.i}"><span class="num">${p.i+1}</span><span class="product"><b>${esc(p.article)}</b><small>${esc(p.name)}${p.pack?`<br>${esc(p.pack)}`:''}</small></span><span class="qty">${p.plan.toLocaleString('ru-RU')}</span><span class="status">${r.done?'Готово':'Ожидает'}</span></div>${open?`<div class="form">${r.alloc.map((a,j)=>allocation(a,j,r.alloc.length)).join('')}<div class="actions"><button class="btn outline" id="split">Разделить размещение</button><button class="btn primary" id="save">Сохранить позицию</button></div></div>`:''}</article>`}).join('')||'<div class="empty">Ничего не найдено</div>'}</section><footer class="finish"><button class="btn primary" id="finish" ${done<total?'disabled':''}>Завершить приёмку</button></footer></div>`;wireHeader();wire()}
function wireHeader(){document.querySelector('#exit').onclick=()=>location.href='/';document.querySelector('#newExcel').onclick=()=>document.querySelector('#excelFile').click();document.querySelector('#excelFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{await loadExcel(file)}catch(error){toast(error.message==='HEADERS'?'Не найдены столбцы «Артикул» или «Наименование»':'Не удалось прочитать товары из Excel')}}}
function wire(){document.querySelector('.search').oninput=e=>{state.query=e.target.value;render()};document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>{state.open=state.open===+x.dataset.open?null:+x.dataset.open;render()});document.querySelectorAll('[data-key]').forEach(x=>x.oninput=()=>{state.rows[state.open].alloc[+x.dataset.a][x.dataset.key]=x.value;persist()});document.querySelectorAll('[data-scan]').forEach(x=>x.onclick=()=>startScanner(+x.dataset.scan));document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{state.rows[state.open].alloc.splice(+x.dataset.remove,1);persist();render()});const split=document.querySelector('#split');if(split)split.onclick=()=>{state.rows[state.open].alloc.push({qty:'',expiry:'',cell:'',comment:''});persist();render()};const save=document.querySelector('#save');if(save)save.onclick=()=>{const row=state.rows[state.open],sum=row.alloc.reduce((s,a)=>s+Number(a.qty||0),0);if(row.alloc.some(a=>!a.qty||!a.expiry||!a.cell))return toast('Заполните количество, срок годности и ячейку');if(sum!==products[state.open].plan)return toast(`Распределено ${sum}, по плану ${products[state.open].plan}`);row.done=true;persist();state.open=Math.min(state.open+1,products.length-1);toast('Позиция сохранена');render()};const finish=document.querySelector('#finish');if(finish)finish.onclick=()=>{state.complete=true;render()}}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
document.querySelector('#closeScanner').onclick=stopScanner;document.querySelector('#scanner').onclick=e=>{if(e.target.id==='scanner')stopScanner()};addEventListener('pagehide',stopScanner);render();
