let products=[];
const saved=JSON.parse(localStorage.getItem('akfix_receiving_current')||'{}');
const state={open:null,query:'',complete:false,fileName:saved.fileName||'',rows:[]};
if(Array.isArray(saved.products)&&saved.products.length){products=saved.products;state.rows=saved.rows||makeRows(products)}
const app=document.querySelector('#app');let scannerStream=null,scannerFrame=0,scanAllocation=null;
const esc=(s='')=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function makeRows(items){return items.map(p=>({done:false,alloc:[{qty:p.plan,expiry:'',cell:'',comment:''}]}))}
let persistTimer;
function snapshot(){return{fileName:state.fileName,products,rows:state.rows}}
function persist(){const value=snapshot();localStorage.setItem('akfix_receiving_current',JSON.stringify(value));clearTimeout(persistTimer);persistTimer=setTimeout(()=>fetch('/api/receiving',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}).catch(()=>{}),400)}
const normalize=value=>String(value??'').trim();
const number=value=>{const parsed=Number(normalize(value).replace(/\s/g,'').replace(',','.'));return Number.isFinite(parsed)?parsed:0};
const column=(headers,patterns)=>headers.findIndex(value=>patterns.some(pattern=>pattern.test(normalize(value))));
async function loadExcel(file){
 let grid=[];
 if(/\.csv$/i.test(file.name)){grid=parseCsv(await file.text())}else{const book=new ExcelJS.Workbook();await book.xlsx.load(await file.arrayBuffer());const sheet=book.worksheets[0];if(sheet)sheet.eachRow({includeEmpty:true},row=>grid.push(row.values.slice(1).map(value=>value?.text??value?.result??value??'')))}if(!grid.length)throw new Error('EMPTY');
 let headerIndex=grid.findIndex(row=>row.some(value=>/артикул|номенклат|товар|колич|план/i.test(normalize(value))));if(headerIndex<0)headerIndex=0;
 const headers=grid[headerIndex].map(normalize),articleCol=column(headers,[/артикул/i,/код/i]),nameCol=column(headers,[/номенклат/i,/наименован/i,/товар/i]),planCol=column(headers,[/план/i,/колич/i,/шт/i]),packCol=column(headers,[/упаков/i,/единиц/i]);if(nameCol<0&&articleCol<0)throw new Error('HEADERS');
 const rows=grid.slice(headerIndex+1).map(row=>({article:normalize(row[articleCol>=0?articleCol:0]),name:normalize(row[nameCol>=0?nameCol:1]),plan:number(row[planCol>=0?planCol:2]),pack:packCol>=0?normalize(row[packCol]):''})).filter(item=>(item.article||item.name)&&item.plan>0);if(!rows.length)throw new Error('ROWS');
 products=rows;state.rows=makeRows(rows);state.fileName=file.name;state.open=0;state.query='';state.complete=false;persist();render();toast(`Загружено позиций: ${rows.length}`)
}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i],next=text[i+1];if(char==='"'&&quoted&&next==='"'){cell+='"';i++}else if(char==='"')quoted=!quoted;else if((char===';'||char===',')&&!quoted){row.push(cell);cell=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i++;row.push(cell);if(row.some(value=>value!==''))rows.push(row);row=[];cell=''}else cell+=char}row.push(cell);if(row.some(value=>value!==''))rows.push(row);return rows}
async function exportExcel(){const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Приёмка');sheet.columns=[{header:'Номенклатура',key:'name',width:42},{header:'Артикул',key:'article',width:18},{header:'Срок годности (месяц и год)',key:'expiry',width:28},{header:'Фактически принято',key:'qty',width:22},{header:'Ячейка',key:'cell',width:18},{header:'Комментарий',key:'comment',width:36}];state.rows.forEach((row,i)=>row.alloc.forEach(a=>sheet.addRow({name:products[i].name,article:products[i].article,expiry:a.expiry,qty:Number(a.qty),cell:a.cell,comment:a.comment})));const blob=new Blob([await book.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`Приёмка — ${state.fileName.replace(/\.[^.]+$/,'')||'результат'}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function stopScanner(){cancelAnimationFrame(scannerFrame);scannerFrame=0;scannerStream?.getTracks().forEach(track=>track.stop());scannerStream=null;document.querySelector('#scannerVideo').srcObject=null;document.querySelector('#scanner').hidden=true}
async function startScanner(index){if(!('BarcodeDetector'in window))return toast('Сканер не поддерживается — введите ячейку вручную');scanAllocation=index;const overlay=document.querySelector('#scanner'),video=document.querySelector('#scannerVideo'),hint=document.querySelector('#scannerHint');overlay.hidden=false;hint.textContent='Запрашиваем доступ к камере…';try{const formats=await BarcodeDetector.getSupportedFormats(),wanted=['qr_code','code_128','code_39','ean_13','ean_8','data_matrix'].filter(x=>formats.includes(x)),detector=new BarcodeDetector(wanted.length?{formats:wanted}:undefined);scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=scannerStream;await video.play();hint.textContent='Наведите камеру на код ячейки';const detect=async()=>{if(!scannerStream)return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){state.rows[state.open].alloc[scanAllocation].cell=codes[0].rawValue.trim();persist();stopScanner();render();toast(`Ячейка: ${codes[0].rawValue.trim()}`);return}}catch{}scannerFrame=requestAnimationFrame(detect)};detect()}catch(error){stopScanner();toast(error.name==='NotAllowedError'?'Разрешите доступ к камере':'Не удалось открыть камеру')}}
function allocation(a,j,total){return`<section class="allocation"><h3>Размещение ${total>1?j+1:''}${total>1?`<button class="remove" data-remove="${j}">Удалить</button>`:''}</h3><div class="grid"><label class="field">Фактически принято<input inputmode="numeric" data-key="qty" data-a="${j}" value="${esc(a.qty)}"></label><label class="field">Срок годности · месяц и год<input type="month" data-key="expiry" data-a="${j}" value="${esc(a.expiry)}"></label><label class="field">Ячейка хранения<span class="cell-control"><input data-key="cell" data-a="${j}" placeholder="Например, A-01-03" value="${esc(a.cell)}"><button type="button" class="scan-cell" data-scan="${j}">Сканировать</button></span></label><label class="field full">Комментарий<input data-key="comment" data-a="${j}" placeholder="Необязательно" value="${esc(a.comment)}"></label></div></section>`}
function header(){return`<header class="top"><img src="/assets/logo.svg" alt="AKFIX"><span><b>Приёмка</b><small>Склад</small></span><div class="top-actions">${products.length?'<button class="header-action" id="newExcel">Загрузить другой Excel</button>':''}<button class="header-action exit" id="exit">Выйти</button></div><input id="excelFile" type="file" accept=".xlsx,.csv" hidden></header>`}
function chooseExcel(){const input=document.querySelector('#excelFile');input.value='';input.click()}
function requestExcel(){if(!products.length){chooseExcel();return}document.querySelector('#replaceExcel').showModal()}
function emptyView(){app.innerHTML=`<div class="shell">${header()}<section class="upload-empty"><div class="upload-mark">XLSX</div><h1>Нет активной приёмки</h1><p>Загрузите актуальный Excel-файл с товарами и плановым количеством.</p><button class="btn primary" id="uploadExcel">Загрузить Excel</button><small>Поддерживаются XLSX и CSV</small></section></div>`;wireHeader();document.querySelector('#uploadExcel').onclick=chooseExcel}
function render(){if(!products.length)return emptyView();if(state.complete){app.innerHTML=`<div class="shell">${header()}<div class="complete"><div class="check">✓</div><h2>Приёмка завершена</h2><p>${esc(state.fileName)} · принято ${state.rows.reduce((s,r)=>s+r.alloc.reduce((x,a)=>x+Number(a.qty||0),0),0).toLocaleString('ru-RU')} шт.</p><button class="btn primary export" id="export">Скачать Excel</button><button class="btn outline" id="return">Вернуться к позициям</button></div></div>`;wireHeader();document.querySelector('#export').onclick=exportExcel;document.querySelector('#return').onclick=()=>{state.complete=false;render()};return}
 const done=state.rows.filter(r=>r.done).length,total=products.length,filtered=products.map((p,i)=>({...p,i})).filter(p=>(p.article+' '+p.name).toLowerCase().includes(state.query.toLowerCase()));
 app.innerHTML=`<div class="shell">${header()}<section class="summary"><h2>${esc(state.fileName.replace(/\.[^.]+$/,''))}</h2><p>${done} из ${total} позиций · данные из Excel</p><div class="progress"><div class="track"><div class="bar" style="width:${done/total*100}%"></div></div><b>${Math.round(done/total*100)}%</b></div></section><input class="search" placeholder="Поиск по артикулу или названию" value="${esc(state.query)}"><div class="labels"><span>Артикул / товар</span><span>План</span><span>Статус</span></div><section>${filtered.map(p=>{const r=state.rows[p.i],open=state.open===p.i;return`<article class="item ${open?'open':''} ${r.done?'done':''}"><div class="item-head" data-open="${p.i}"><span class="num">${p.i+1}</span><span class="product"><b>${esc(p.article)}</b><small>${esc(p.name)}${p.pack?`<br>${esc(p.pack)}`:''}</small></span><span class="qty">${p.plan.toLocaleString('ru-RU')}</span><span class="status">${r.done?'Готово':'Ожидает'}</span></div>${open?`<div class="form">${r.alloc.map((a,j)=>allocation(a,j,r.alloc.length)).join('')}<div class="actions"><button class="btn outline" id="split">Разделить размещение</button><button class="btn primary" id="save">Сохранить позицию</button></div></div>`:''}</article>`}).join('')||'<div class="empty">Ничего не найдено</div>'}</section><footer class="finish"><button class="btn primary" id="finish" ${done<total?'disabled':''}>Завершить приёмку</button></footer></div>`;wireHeader();wire()}
function wireHeader(){document.querySelector('#exit').onclick=async()=>{localStorage.removeItem('akfix_last_user');await fetch('/api/logout',{method:'POST'}).catch(()=>{});location.href='/'};const newExcel=document.querySelector('#newExcel');if(newExcel)newExcel.onclick=requestExcel;document.querySelector('#excelFile').onchange=async e=>{const input=e.target,file=input.files[0];if(!file)return;const button=document.querySelector('#newExcel')||document.querySelector('#uploadExcel');if(button){button.disabled=true;button.textContent='Читаем файл…'}try{await loadExcel(file)}catch(error){if(button){button.disabled=false;button.textContent=products.length?'Загрузить другой Excel':'Загрузить Excel'}toast(error.message==='HEADERS'?'Не найдены столбцы «Артикул» или «Наименование»':'Не удалось прочитать товары из Excel')}finally{input.value=''}}}
function wire(){document.querySelector('.search').oninput=e=>{state.query=e.target.value;render()};document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>{state.open=state.open===+x.dataset.open?null:+x.dataset.open;render()});document.querySelectorAll('[data-key]').forEach(x=>x.oninput=()=>{state.rows[state.open].alloc[+x.dataset.a][x.dataset.key]=x.value;persist()});document.querySelectorAll('[data-scan]').forEach(x=>x.onclick=()=>startScanner(+x.dataset.scan));document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{state.rows[state.open].alloc.splice(+x.dataset.remove,1);persist();render()});const split=document.querySelector('#split');if(split)split.onclick=()=>{state.rows[state.open].alloc.push({qty:'',expiry:'',cell:'',comment:''});persist();render()};const save=document.querySelector('#save');if(save)save.onclick=()=>{const row=state.rows[state.open],sum=row.alloc.reduce((s,a)=>s+Number(a.qty||0),0);if(row.alloc.some(a=>!a.qty||!a.expiry||!a.cell))return toast('Заполните количество, срок годности и ячейку');if(sum!==products[state.open].plan)return toast(`Распределено ${sum}, по плану ${products[state.open].plan}`);row.done=true;persist();state.open=Math.min(state.open+1,products.length-1);toast('Позиция сохранена');render()};const finish=document.querySelector('#finish');if(finish)finish.onclick=()=>{state.complete=true;render()}}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function hydrate(){try{const response=await fetch('/api/receiving',{cache:'no-store'});if(response.status===401){location.href='/';return}if(response.ok){const remote=(await response.json()).item;if(remote?.products?.length){products=remote.products;state.fileName=remote.fileName||'';state.rows=remote.rows||makeRows(products)}}}catch{}render()}
document.querySelector('#closeScanner').onclick=stopScanner;document.querySelector('#scanner').onclick=e=>{if(e.target.id==='scanner')stopScanner()};addEventListener('pagehide',stopScanner);hydrate();
document.querySelector('#cancelReplace').onclick=()=>document.querySelector('#replaceExcel').close();document.querySelector('#confirmReplace').onclick=()=>{document.querySelector('#replaceExcel').close();chooseExcel()};
